project:
  type: website
  output-dir: docs
  resources:
    - "bibtex"
    - "images"

execute:
  freeze: auto

website:
  title: "./jrfep"
  repo-url: https://github.com/jrfep/eng
  repo-branch: mostly-harmless
  repo-actions: [edit, issue]
  navbar:
    title: "J.R. Ferrer-Paris"
    type: inverse
    left:
      - icon: book-half
        text: "My research"
        menu:
        - CV.qmd
        - my-publications.qmd
        - impact-SDG.qmd
    right:
      - icon: folder-symlink
        menu:
        - text: "Overview"
          icon: projector
          href: "https://jrfep.github.io/"
        - text: "Read more here"
          icon: eyeglasses
          href: links.qmd
        - text: "cambiar a Español"
          icon: braces-asterisk
          href: "https://jrfep.github.io/esp/"

bibliography: 
  - bibtex/peer-review.bibtex
csl: bibtex/my.csl

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
lang: en