project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "./jrfep"
  repo-url: https://github.com/jrfep/eng
  repo-branch: mostly-harmless
  repo-actions: [edit, issue]
  navbar:
    title: "J.R. Ferrer-Paris"
    type: inverse
    left:
      - CV.qmd
    right:
      - text: "Read more here"
        icon: eyeglasses
        href: links.qmd
      - icon: folder-symlink
        menu:
        - text: "Overview"
          icon: projector
          href: "https://jrfep.github.io/"
        - text: "cambiar a Español"
          icon: braces-asterisk
          href: "https://jrfep.github.io/esp/"

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
lang: en